export const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    FETCH_PRODUCTS: 'FETCH_PRODUCTS', 
    ADD_FAVORITE: 'ADD_FAVORITE',
    REMOVE_FAVORITE_PRODUCT: 'REMOVE_FAVORITE_PRODUCT',
    ADD_FILTER_PRODUCTS: 'ADD_FILTER_PRODUCTS' 
} 